### ISSUE TITLE
Cannot register all custom widgets at central place

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [RealyUniqueName/StablexUI#201]
Hey,

I have a custom widget, which I use at several places. In my mein function I register it before I load the main gui:

Main.hx
```
   UIBuilder.regClass('CustomWidget');
   var gui = UIBuilder.buildFn('guiUsingCustomWidget.xml')();
```

Now I have other gui parts (popup), which I load at another place:

CustomPopups.hx:
```
   var popup = UIBuilder.buildFn('popupUsingCustomWidget.xml')();
```

Leading to this error:

```
    Source/controllers/CustomPopups.hx:94: characters 17-65 : Widget class is not registered: CustomWidget
```

The workaround is removing the registration of the CustomWidget from Main and put it into CustomPopup.

Works, but is not nice. I want my global custom widgets to be registered at a central position.

**Comment by RealyUniqueName** [comment]
This happens because compiler finds your `CustomPopup` module earlier than your main function.
You can solve this by creating separate module with macro method, but without additional imports except `ru.stablex.ui.UIBuilder` and register your custom widgets in that module. 
Like this one: https://github.com/RealyUniqueName/StablexUI/blob/master/samples/xmlClasses/com/example/Init.hx
And invoke that method using `--macro` compiler flag.

**Comment by RudolfVonKrugstein** [comment]
Works, thanks!
